#76 adding support embedded avro docs
corunet/kloadgen pull request #142
Opened 2021-11-22 15:20 UTC by vtorresb

2021-11-26 11:09 UTC, Rivarsal requested changes
Have to check why the processor doesn´t get the schema when we have an EmbeddedSchema in an Avro

2021-12-07 09:56 UTC, kszosze approved these changes
Clean to merge once the requested changes were done

2021-12-07 10:14 UTC, kszosze approved these changes

2021-12-27 16:26 UTC, kszosze approved these changes

2021-12-28 22:07 UTC, merged