Update readme
corunet/kloadgen pull request #229
Opened 2022-04-27 17:54 UTC by esthertrigo

Closes #227 

I am keeping it in draft until it can be merged, once the files in /docs have been moved to the wiki.

2022-04-28 06:31 UTC, Rivarsal approved these changes

2022-06-22 06:24 UTC, jgbriz submitted a review, later dismissed

2022-06-22 09:03 UTC, fcampostato approved these changes

2022-06-22 10:57 UTC, fcampostato requested changes

2022-06-22 10:57 UTC, fcampostato commented on config/OSS_style_idea.xml
>        <option name="TAB_SIZE" value="2" />
Consider adding `USE_RELATIVE_INDENTS` with value true to avoid checkstyle warnings when method parameters are carried over a new line.

2022-06-23 14:27 UTC, IsaUlloa submitted a review, later dismissed

2022-06-24 06:19 UTC, jemacineiras approved these changes

2022-07-04 07:46 UTC, fcampostato approved these changes

2022-07-04 12:04 UTC, jemacineiras approved these changes

2022-07-04 12:12 UTC, merged